### ISSUE TITLE
Example Bluetooth MBlock5 lỗi

### ISSUE THREAD

**Issue by devshop2019** [makerlabvn/RoverBot#1]
Robot chạy hoài không dừng được khi ngắt kết nối Bluetooth

**Comment by MinhKhanh614** [comment]
fixed
![mblock_wroverBluetooth_240728](https://github.com/user-attachments/assets/8e6fa83d-aee6-40e2-aec0-69875ecc426d)

**Comment by MinhKhanh614** [comment]
fixed
![mblock_wroverBluetooth_240728](https://github.com/user-attachments/assets/82742c6d-e87c-4d13-b859-809ac000e07d)
